apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: react-movie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-movie-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-movie
  template:
    metadata:
      labels:
        app: react-movie
    spec:
      containers:
      - name: react-container
        image: 947841444229.dkr.ecr.us-east-2.amazonaws.com/react-image:214330a64d80479695c9293af6e6858d92bd46bb
        ports:
        - containerPort: 3000  
