name: Deploy to ECR

on:
 
  push:
    branches: ['master']

jobs:
  build-and-push-docker-image-to-ECR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: vitr/actions-build-and-upload-to-ecs@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: react-image
          region: us-east-2
          tags: ${{ github.sha }}
          create_repo: true
        
  update-k8s-manifest:
    runs-on: ubuntu-latest 
    needs: ['build-and-push-docker-image-to-ECR']
    steps:
      - uses: actions/checkout@v3
        with: 
          repository: vikashkumar0712/manifest-yaml
          ref: 'main'
          token: ${{ secrets.G_TOKEN2 }}
      - name: setup git config
        run: |
          git config --global user.email "chiragdksh@gmail.com"
          git config --global user.name "vikashkumar0712"
          echo ${{ github.sha }}
          sed -i 's+947841444229.dkr.ecr.us-east-2.amazonaws.com/react-image:.*+947841444229.dkr.ecr.us-east-2.amazonaws.com/react-image:${{ github.sha }}+g' deployment.yaml
          git add -A
          git commit -m "Update image for - ${{ github.sha }}"
      - run: echo ${{ github }}
      - run: git push origin main
